### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by ghost** [gitlabhq/mysql-postgresql-converter#11]
I've got the following error during conversion of gitlab mysql database to postgress format:

```
[root@devel gitlab]# sudo -u git -H python mysql-postgresql-converter/db_converter.py gitlabhq_production.mysql db/database.sql
Traceback (most recent call last):
  File "mysql-postgresql-converter/db_converter.py", line 256, in <module>
    parse(sys.argv[1], sys.argv[2])
  File "mysql-postgresql-converter/db_converter.py", line 25, in parse
    num_lines = int(subprocess.check_output(["wc", "-l", input_filename]).strip().split()[0])
AttributeError: 'module' object has no attribute 'check_output'
```

My python is 2.7:

```
[root@devel gitlab]# python -V
Python 2.7.10 :: Continuum Analytics, Inc.
```

(Using the manual https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/mysql_to_postgresql.md )

**Comment by axilleas** [comment]
Can you try without changing to the git user?

```
python mysql-postgresql-converter/db_converter.py gitlabhq_production.mysql db/database.sql
```

**Comment by ulrith** [comment]
The result is the same:

    [root@devel gitlab]# python mysql-postgresql-converter/db_converter.py gitlabhq_production.mysql db/database.sql
    Traceback (most recent call last):
      File "mysql-postgresql-converter/db_converter.py", line 256, in <module>
        parse(sys.argv[1], sys.argv[2])
      File "mysql-postgresql-converter/db_converter.py", line 25, in parse
        num_lines = int(subprocess.check_output(["wc", "-l", input_filename]).strip().split()[0])
    AttributeError: 'module' object has no attribute 'check_output'

**Comment by ghost** [comment]
This has solved the problem. Thank you!

**Comment by axilleas** [comment]
Yeah, thought it had to do something with git user not picking the `subprocess` class. Glad you got it solved :)
