### ISSUE TITLE
sha varbinary utf-8 problem

### ISSUE THREAD

**Issue by krzaczek** [gitlabhq/mysql-postgresql-converter#14]
Hi,

Gitlab 9.4.1
Mysql 5.7.17-13

Im trying to migrate from mysql to postgres but having problem converting sql. The script throws and error about utf-8 encoding. The mysqldump file is correctly encoded in utf-8 but the script is having problems with `sha` column in `merge_request_diff_commits`

```bash
root@gitlab:/home/git/gitlab/tmp/backups/db# sudo -u git -H python mysql-postgresql-converter/db_converter.py gitlabhq_production.mysql db/database.sql
Line 1587 (of 3404: 46.62%) [43 tables] [40 inserts] [ETA: 0 min 0 sec]Traceback (most recent call last):
  File "mysql-postgresql-converter/db_converter.py", line 256, in <module>
    parse(sys.argv[1], sys.argv[2])
  File "mysql-postgresql-converter/db_converter.py", line 73, in parse
    line = line.decode("utf8").strip().replace(r"\\", "WUBWUBREALSLASHWUB").replace(r"\0", "").replace(r"\'", "''").replace("WUBWUBREALSLASHWUB", r"\\")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 101-102: invalid continuation byte
```

```sql
INSERT INTO "merge_request_diff_commits" VALUES ('2017-07-24 12:33:37','2017-07-24 12:33:37',271,0,'N?W??b?3p?ߵ+?7?q8','Paweł Krzaczkowski','pawel@freshmind.pl','Paweł Krzaczkowski','pawel@freshmind.pl','WIP #26 - print multiple invoices from manage\n')
```

The 101 position is the beginning of SHA column `,'N?W??b?3p?ߵ+?7?q8',`

**Comment by grzesiek** [comment]
@krzaczek I believe that this is a known problem, it is either fixed or will be in the next patch release. Feel free to reopen this issue in a relevant issue tracker on gitlab.com! /cc @smcgivern

**Comment by smcgivern** [comment]
@grzesiek this is a different issue 😃 

@krzaczek that column is a `blob` column in MySQL, and a `bytea` column in Postgres. I guess this script doesn't handle that, as it's providing a string literal instead of a binary literal, and I think the only way we could is to hard-code the column names that we know are of this type (typically they are called `sha`). @YorickPeterse any ideas?

**Comment by godfat** [comment]
I don't know about the issue here, but if people are trying to migrate from MySQL to PostgreSQL for GitLab, we are investigating using pgloader instead of this script.

Please see the discussion over https://gitlab.com/gitlab-org/gitlab-ee/issues/2799

**Comment by krzaczek** [comment]
@smcgivern Yep I was able to migrate by manually changing field type to `bytea` and truncating this table (for testing purpuses). This allowed me to generate the new .sql import for postgres
