### ISSUE TITLE
Default values for boolean fields are not preserved?

### ISSUE THREAD

**Issue by jacobvosmaer** [gitlabhq/mysql-postgresql-converter#2]
https://gitlab.com/gitlab-org/gitlab-ce/issues/1520#note_1197200

@DouweM wrote:

> I think this line: https://github.com/gitlabhq/mysql-postgresql-converter/blob/gitlab/db_converter.py#L158 converts tinyint(1), which MySQL uses for boolean, to a PostgreSQL boolean field, but for some reason it also runs `ALTER TABLE \"%s\" ALTER COLUMN \"%s\" DROP DEFAULT`. Does this make sense to you? I think we need to update the converter.

**Comment by dosire** [comment]
@DouweM can you try to fix this?

**Comment by DouweM** [comment]
Yeah I'll look into it.

**Comment by dosire** [comment]
@DouweM Thanks!
